#ifndef ENTITY_CORE_FFI_H
#define ENTITY_CORE_FFI_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes returned by FFI functions.
 */
typedef enum EntityCoreError {
  Ok = 0,
  InvalidArgument = 1,
  NotFound = 2,
  PermissionDenied = 3,
  StorageError = 4,
  NetworkError = 5,
  EncodingError = 6,
  CryptoError = 7,
  InternalError = 99,
} EntityCoreError;

/**
 * A buffer of bytes owned by the FFI layer.
 *
 * Callers must free with `entity_core_buffer_free`.
 */
typedef struct EntityCoreBuffer {
  uint8_t *data;
  uintptr_t len;
} EntityCoreBuffer;

/**
 * Opaque handle type for FFI objects.
 */
typedef uint64_t EntityCoreHandle;

/**
 * Free a buffer previously returned by the FFI.
 *
 * # Safety
 * Must only be called once on a buffer returned by this library.
 */
void entity_core_buffer_free(struct EntityCoreBuffer buf);

/**
 * Get a pointer to the last error message for the current thread.
 *
 * Returns null if no error has been set. The pointer is valid until the
 * next FFI call on the same thread.
 */
const char *entity_core_last_error(void);

/**
 * Create a CBOR text string value.
 *
 * # Safety
 * `ptr` must point to `len` valid UTF-8 bytes.
 */
EntityCoreHandle ecf_value_text(const uint8_t *ptr, uintptr_t len);

/**
 * Create a CBOR byte string value.
 *
 * # Safety
 * `ptr` must point to `len` valid bytes.
 */
EntityCoreHandle ecf_value_bytes(const uint8_t *ptr, uintptr_t len);

/**
 * Create a CBOR integer value.
 */
EntityCoreHandle ecf_value_integer(int64_t val);

/**
 * Create a CBOR boolean value.
 */
EntityCoreHandle ecf_value_bool(bool val);

/**
 * Create a CBOR null value.
 */
EntityCoreHandle ecf_value_null(void);

/**
 * Create a CBOR float value.
 */
EntityCoreHandle ecf_value_float(double val);

/**
 * Create a CBOR array from an array of value handles.
 *
 * # Safety
 * `handles` must point to `count` valid `Handle` values.
 */
EntityCoreHandle ecf_value_array(const EntityCoreHandle *handles, uintptr_t count);

/**
 * Create an empty CBOR map value.
 */
EntityCoreHandle ecf_value_map_new(void);

/**
 * Insert a key-value pair into a map. Consumes the key and value handles.
 */
enum EntityCoreError ecf_value_map_insert(EntityCoreHandle map_handle,
                                          EntityCoreHandle key_handle,
                                          EntityCoreHandle value_handle);

/**
 * Free a value handle.
 */
void ecf_value_free(EntityCoreHandle handle);

/**
 * Encode a value to ECF (deterministic CBOR) bytes. Consumes the handle.
 */
struct EntityCoreBuffer ecf_encode(EntityCoreHandle handle);

/**
 * Decode ECF/CBOR bytes into a value handle.
 *
 * # Safety
 * `ptr` must point to `len` valid bytes of CBOR data.
 */
EntityCoreHandle ecf_decode(const uint8_t *ptr, uintptr_t len);

/**
 * Encode CBOR bytes to diagnostic notation string.
 *
 * # Safety
 * `ptr` must point to `len` valid bytes of CBOR data.
 */
struct EntityCoreBuffer ecf_to_diag(const uint8_t *ptr, uintptr_t len);

/**
 * Parse CBOR diagnostic notation to bytes.
 *
 * # Safety
 * `ptr` must point to `len` valid UTF-8 bytes.
 */
struct EntityCoreBuffer ecf_from_diag(const uint8_t *ptr, uintptr_t len);

/**
 * Compute the content hash of an entity (type + data).
 *
 * Returns 33 bytes (algorithm byte + 32-byte SHA-256 digest).
 *
 * # Safety
 * `type_ptr`/`type_len` and `data_ptr`/`data_len` must be valid.
 */
struct EntityCoreBuffer entity_hash_compute(const uint8_t *type_ptr,
                                            uintptr_t type_len,
                                            const uint8_t *data_ptr,
                                            uintptr_t data_len);

/**
 * Validate that a hash matches the given type + data.
 *
 * # Safety
 * All pointer/length pairs must be valid. `hash_ptr` must point to 33 bytes.
 */
enum EntityCoreError entity_hash_validate(const uint8_t *type_ptr,
                                          uintptr_t type_len,
                                          const uint8_t *data_ptr,
                                          uintptr_t data_len,
                                          const uint8_t *hash_ptr);

/**
 * Format a 33-byte hash as hex string.
 *
 * # Safety
 * `hash_ptr` must point to 33 valid bytes.
 */
struct EntityCoreBuffer entity_hash_to_hex(const uint8_t *hash_ptr);

/**
 * Parse a hex string back to 33-byte hash.
 *
 * # Safety
 * `hex_ptr`/`hex_len` must point to a valid hex string (66 chars).
 */
struct EntityCoreBuffer entity_hash_from_hex(const uint8_t *hex_ptr, uintptr_t hex_len);

/**
 * Format a 33-byte hash as the display string ("ecfv1-sha256:...").
 *
 * # Safety
 * `hash_ptr` must point to 33 valid bytes.
 */
struct EntityCoreBuffer entity_hash_to_display(const uint8_t *hash_ptr);

/**
 * Generate a new random Ed25519 keypair.
 */
EntityCoreHandle entity_keypair_generate(void);

/**
 * Create an Ed25519 keypair from a 32-byte seed (deterministic).
 *
 * # Safety
 * `seed_ptr` must point to exactly 32 bytes.
 */
EntityCoreHandle entity_keypair_from_seed(const uint8_t *seed_ptr);

/**
 * Free a keypair handle.
 */
void entity_keypair_free(EntityCoreHandle handle);

/**
 * Get the 32-byte public key from a keypair.
 */
struct EntityCoreBuffer entity_keypair_public_key(EntityCoreHandle handle);

/**
 * Get the PeerID string for a keypair.
 */
struct EntityCoreBuffer entity_keypair_peer_id(EntityCoreHandle handle);

/**
 * Sign a message with a keypair. Returns 64-byte Ed25519 signature.
 *
 * # Safety
 * `msg_ptr`/`msg_len` must be valid.
 */
struct EntityCoreBuffer entity_sign(EntityCoreHandle handle,
                                    const uint8_t *msg_ptr,
                                    uintptr_t msg_len);

/**
 * Verify an Ed25519 signature.
 *
 * # Safety
 * `pubkey_ptr` must point to 32 bytes, `sig_ptr` to 64 bytes,
 * `msg_ptr`/`msg_len` must be valid.
 */
enum EntityCoreError entity_verify(const uint8_t *pubkey_ptr,
                                   const uint8_t *msg_ptr,
                                   uintptr_t msg_len,
                                   const uint8_t *sig_ptr,
                                   uintptr_t sig_len);

/**
 * Create a new entity from type string and CBOR data bytes.
 *
 * Computes the content hash. Returns 0 on error.
 *
 * # Safety
 * `type_ptr`/`type_len` must be valid UTF-8, `data_ptr`/`data_len` must be valid bytes.
 */
EntityCoreHandle entity_new(const uint8_t *type_ptr,
                            uintptr_t type_len,
                            const uint8_t *data_ptr,
                            uintptr_t data_len);

/**
 * Free an entity handle.
 */
void entity_free(EntityCoreHandle handle);

/**
 * Get the entity type string as a buffer.
 */
struct EntityCoreBuffer entity_get_type(EntityCoreHandle handle);

/**
 * Get the entity data bytes as a buffer.
 */
struct EntityCoreBuffer entity_get_data(EntityCoreHandle handle);

/**
 * Get the entity content hash as 33 bytes.
 */
struct EntityCoreBuffer entity_get_hash(EntityCoreHandle handle);

/**
 * Validate an entity's content hash.
 */
enum EntityCoreError entity_validate(EntityCoreHandle handle);

/**
 * Encode an entity to wire format (CBOR bytes: {type, data, content_hash}).
 * Does NOT consume the entity handle.
 */
struct EntityCoreBuffer entity_encode(EntityCoreHandle handle);

/**
 * Decode wire-format CBOR bytes into an entity handle.
 *
 * # Safety
 * `ptr`/`len` must point to valid CBOR bytes.
 */
EntityCoreHandle entity_decode(const uint8_t *ptr, uintptr_t len);

/**
 * Initialize the FFI runtime. Must be called before any peer operations.
 * Returns 0 on success, -1 on error.
 */
int32_t entity_core_init(void);

/**
 * Shutdown the FFI runtime. Call when done with the library.
 */
void entity_core_shutdown(void);

/**
 * Get the library version string.
 */
struct EntityCoreBuffer entity_core_version(void);

/**
 * Create a new peer from a 32-byte seed. Returns a handle, or 0 on error.
 *
 * Uses the global runtime created by `entity_core_init()`.
 *
 * # Safety
 * `seed_ptr` must point to 32 bytes. `addr_ptr`/`addr_len` must be valid UTF-8.
 */
EntityCoreHandle entity_core_peer_create(const uint8_t *seed_ptr,
                                         const uint8_t *addr_ptr,
                                         uintptr_t addr_len);

/**
 * Free a peer handle (stops the peer if running).
 */
void entity_core_peer_free(EntityCoreHandle handle);

/**
 * Get the peer's PeerID string.
 */
struct EntityCoreBuffer entity_core_peer_id(EntityCoreHandle handle);

/**
 * Start the peer listening (non-blocking — spawns in background).
 *
 * Starts extension engines (clock, sync, subscription) and the TCP accept loop.
 * Returns 0 on success.
 */
enum EntityCoreError entity_core_peer_start(EntityCoreHandle handle);

/**
 * Execute a local handler operation. Returns an entity handle for the result, or 0 on error.
 *
 * `params_entity` is consumed (freed) by this call.
 *
 * # Safety
 * `handler_ptr`/`handler_len` and `operation_ptr`/`operation_len` must be valid UTF-8.
 */
EntityCoreHandle entity_core_execute(EntityCoreHandle peer_handle,
                                     const uint8_t *handler_ptr,
                                     uintptr_t handler_len,
                                     const uint8_t *operation_ptr,
                                     uintptr_t operation_len,
                                     EntityCoreHandle params_entity);

/**
 * Subscribe to tree change events for a peer.
 * Returns a subscription handle, or 0 on error.
 *
 * Use `entity_core_poll_event()` to poll events and
 * `entity_core_unsubscribe()` to free the subscription.
 */
EntityCoreHandle entity_core_subscribe(EntityCoreHandle peer_handle);

/**
 * Poll for the next event from a subscription (non-blocking).
 *
 * Returns a buffer containing `path\0hash_bytes` (path as UTF-8, null byte separator,
 * then 33 hash bytes). Returns a null buffer if no events are pending.
 */
struct EntityCoreBuffer entity_core_poll_event(EntityCoreHandle sub_handle);

/**
 * Free a subscription handle.
 */
void entity_core_unsubscribe(EntityCoreHandle sub_handle);

/**
 * Get an entity from the tree by path.
 *
 * # Safety
 * `path_ptr`/`path_len` must be valid UTF-8.
 */
EntityCoreHandle entity_core_tree_get(EntityCoreHandle handle,
                                      const uint8_t *path_ptr,
                                      uintptr_t path_len);

/**
 * Put an entity into the tree at a path. Returns the 33-byte content hash.
 *
 * # Safety
 * `path_ptr`/`path_len` must be valid UTF-8.
 */
struct EntityCoreBuffer entity_core_tree_put(EntityCoreHandle peer_handle,
                                             const uint8_t *path_ptr,
                                             uintptr_t path_len,
                                             EntityCoreHandle entity_handle);

/**
 * List paths under a prefix. Returns a null-separated list of path strings.
 *
 * # Safety
 * `prefix_ptr`/`prefix_len` must be valid UTF-8.
 */
struct EntityCoreBuffer entity_core_tree_list(EntityCoreHandle handle,
                                              const uint8_t *prefix_ptr,
                                              uintptr_t prefix_len);

#endif  /* ENTITY_CORE_FFI_H */
